Repository hmcts/camunda-bpm, pull requests merged in 2021-05, with the labels that each got.

#165 Added Civil group
  src/main/resources/application.yaml
Labels: ns:camunda, prd:camunda, rel:camunda-bpm-pr-165

#168 Add basic optimize docs
  README.md
Labels: ns:camunda, prd:camunda, rel:camunda-bpm-pr-168

#169 Update application.yaml
  src/main/resources/application.yaml
Labels: ns:camunda, prd:camunda, rel:camunda-bpm-pr-169

#170 Add error log
  src/main/java/uk/gov/hmcts/reform/camunda/bpm/services/TaskConfigurationService.java
Labels: ns:camunda, prd:camunda, rel:camunda-bpm-pr-170
