Repository hmcts/camunda-bpm, pull requests merged in 2021-04, with the labels that each got.

#137 Upgrade Camunda and springboot to 2.4
  build.gradle
  charts/camunda-bpm/Chart.yaml
  charts/camunda-bpm/values.yaml
  src/main/resources/application.yaml
  src/main/resources/bootstrap.yaml
Labels: ns:camunda, prd:camunda, rel:camunda-bpm-pr-137

#138 move to vault master
  infrastructure/vault.tf
Labels: ns:camunda, prd:camunda, rel:camunda-bpm-pr-138

#141 Upgrade azurerm and tf
  infrastructure/.terraform-version
  infrastructure/main.tf
Labels: ns:camunda, prd:camunda, rel:camunda-bpm-pr-141

#145 Fix spring profiles
  src/main/resources/application.yaml
Labels: ns:camunda, prd:camunda, rel:camunda-bpm-pr-145

#144 DTSPO-2371 Creating AppInsight
  infrastructure/main.tf
Labels: ns:camunda, prd:camunda, rel:camunda-bpm-pr-144

#146 remove default password
  src/main/resources/application.yaml
Labels: ns:camunda, prd:camunda, rel:camunda-bpm-pr-146

#147 Upgrade DB to 7.15
  charts/camunda-bpm/Chart.yaml
  charts/camunda-bpm/values.yaml
  src/main/resources/db/migration/V4_postgres_engine_7.13_patch_7.13.4_to_7.13.5_1.sql
  src/main/resources/db/migration/V5_postgres_engine_7.13_patch_7.13.4_to_7.13.5_2.sql
  src/main/resources/db/migration/V6_postgres_engine_7.13_patch_7.13.5_to_7.13.6.sql
  src/main/resources/db/migration/V7_postgres_engine_7.13_to_7.14.sql
  src/main/resources/db/migration/V8_postgres_engine_7.14_to_7.15.sql
Labels: ns:camunda, prd:camunda, rel:camunda-bpm-pr-147

#149 Add empty defaults for oauth2 client secrets
  src/main/resources/application.yaml
Labels: ns:camunda, prd:camunda, rel:camunda-bpm-pr-149

#151 fixing jaxb errors
  build.gradle
Labels: ns:camunda, prd:camunda, rel:camunda-bpm-pr-151

#152 Adding appinssights
  charts/camunda-bpm/Chart.yaml
  charts/camunda-bpm/values.yaml
Labels: ns:camunda, prd:camunda, rel:camunda-bpm-pr-152

#156 RWA-514: Migrating to task variables
  src/main/java/uk/gov/hmcts/reform/camunda/bpm/config/EventHandlerConfiguration.java
  src/main/java/uk/gov/hmcts/reform/camunda/bpm/services/TaskConfigurationService.java
  src/test/java/uk/gov/hmcts/reform/camunda/bpm/services/TaskConfigurationServiceTest.java
Labels: ns:camunda, prd:camunda, rel:camunda-bpm-pr-156
