Repository hmcts/camunda-bpm, pull requests merged in 2022-08, with the labels that each got.

#343 DTSPO-6156 - Upgrade Camunda Version
  build.gradle
Labels: ns:camunda, prd:camunda, rel:camunda-bpm-pr-343

#352 Add migration scripts for 7.17
  build.gradle
  src/main/resources/db/migration/V10__postgres_engine_7.16_to_7.17.sql
Labels: ns:camunda, prd:camunda, rel:camunda-bpm-pr-352

#366 Add backstage configuration file
  catalog-info.yaml
Labels: ns:camunda, prd:camunda, rel:camunda-bpm-pr-366

#367 DTSPO-6156 - Migrate App Insights from instrumentation keys to connection strings
  .gitignore
  Dockerfile
  build.gradle
  charts/camunda-bpm/Chart.yaml
  charts/camunda-bpm/values.yaml
  infrastructure/app-insights.tf
  lib/AI-Agent.xml
  lib/applicationinsights.json
Labels: ns:camunda, prd:camunda, add-or-update, rel:camunda-bpm-pr-367

#368 DTSPO-6156 - Migrate Camunda app to Java 17
  Dockerfile
  build.gradle
  charts/camunda-bpm/Chart.yaml
Labels: ns:camunda, prd:camunda, rel:camunda-bpm-pr-368

#369 DTSPO-6156 - Remove app insights instrumentation key
  charts/camunda-bpm/Chart.yaml
  charts/camunda-bpm/values.yaml
Labels: ns:camunda, prd:camunda, rel:camunda-bpm-pr-369

#374 Increase SKU and Storage on Camunda AAT DB
  infrastructure/aat.tfvars
  infrastructure/db.tf
  infrastructure/variables.tf
Labels: ns:camunda, prd:camunda, add-or-update, rel:camunda-bpm-pr-374

#376 Increase SKU and Storage on Camunda AAT DB
  infrastructure/aat.tfvars
  infrastructure/db.tf
  infrastructure/variables.tf
Labels: ns:camunda, prd:camunda, add-or-update, rel:camunda-bpm-pr-376
