Repository hmcts/camunda-bpm, pull requests merged in 2022-09, with the labels that each got.

#382 Setup multi arch for Camuna BPM
  .dockerignore
  Dockerfile
  acb.tpl.yaml
  config/owasp/suppressions.xml
Labels: ns:camunda, prd:camunda, rel:camunda-bpm-pr-382

#389 RWA-1765 change camunda artifactory domain name
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:camunda, prd:camunda, rel:camunda-bpm-pr-389

#383 RWA-1521 Camunda - Switch off Task configuration code
  src/main/java/uk/gov/hmcts/reform/camunda/bpm/config/EventHandlerConfiguration.java
  src/test/java/uk/gov/hmcts/reform/camunda/bpm/config/EventHandlerConfigurationTest.java
Labels: ns:camunda, prd:camunda, rel:camunda-bpm-pr-383
