Repository hmcts/camunda-bpm, pull requests merged in 2022-10, with the labels that each got.

#402 Suppressing CVE to continue RWA-1521 deployment
  config/owasp/suppressions.xml
Labels: ns:camunda, prd:camunda, rel:camunda-bpm-pr-402

#379 RWA-1522 - Remove task configuration code
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/reform/camunda/bpm/config/EventHandlerConfiguration.java
  src/test/java/uk/gov/hmcts/reform/camunda/bpm/config/EventHandlerConfigurationTest.java
Labels: ns:camunda, prd:camunda, rel:camunda-bpm-pr-379

#403 Adding tenant for Private Law
  src/main/resources/application.yaml
Labels: ns:camunda, prd:camunda, rel:camunda-bpm-pr-403

#404 Add new team onboarding doc
  README.md
Labels: ns:camunda, prd:camunda, rel:camunda-bpm-pr-404

#410 Adding ET tenant
  src/main/resources/application.yaml
Labels: ns:camunda, prd:camunda, rel:camunda-bpm-pr-410
