Repository hmcts/camunda-bpm, pull requests merged in 2023-12, with the labels that each got.

#704 fix flyway postgresql
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:camunda, prd:camunda, rel:camunda-bpm-pr-704

#705 add flyway postgresql to buildscript
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:camunda, prd:camunda, rel:camunda-bpm-pr-705

#711 DTSPO-16178 moving App insight to use module
  config/owasp/suppressions.xml
  infrastructure/app-insights.tf
  infrastructure/main.tf
Labels: ns:camunda, prd:camunda, add-or-update, rel:camunda-bpm-pr-711
