Repository hmcts/camunda-bpm, pull requests merged in 2023-06, with the labels that each got.

#540 DTSPO-13682 - Update values to flexible server
  charts/camunda-bpm/Chart.yaml
  charts/camunda-bpm/values.yaml
Labels: ns:camunda, prd:camunda, DO_NOT_MERGE, rel:camunda-bpm-pr-540

#562 DTSPO-13692 - Delete single server
  infrastructure/db.tf
Labels: ns:camunda, prd:camunda, destroy, rel:camunda-bpm-pr-562

#563 DTSPO-13692 - Allow nested resource deletion
  infrastructure/provider.tf
Labels: ns:camunda, prd:camunda, destroy, rel:camunda-bpm-pr-563

#568 DTSPO-13692 - Update values
  charts/camunda-bpm/Chart.yaml
  charts/camunda-bpm/values.yaml
Labels: ns:camunda, prd:camunda, rel:camunda-bpm-pr-568

#569 DTSPO-13692 - Remove v14 secrets
  infrastructure/db.tf
Labels: ns:camunda, prd:camunda, destroy, rel:camunda-bpm-pr-569

#572 DTSPO-14167: Update Camunda Version
  build.gradle
Labels: ns:camunda, prd:camunda, rel:camunda-bpm-pr-572

#573 Sample health requests aggressively
  lib/applicationinsights.json
Labels: ns:camunda, prd:camunda, rel:camunda-bpm-pr-573

#580 Revert "DTSPO-14167: Update Camunda Version"
  build.gradle
Labels: ns:camunda, prd:camunda, rel:camunda-bpm-pr-580
