Repository hmcts/camunda-bpm, pull requests merged in 2023-07, with the labels that each got.

#594 Update suppressions.xml
  config/owasp/suppressions.xml
Labels: ns:camunda, prd:camunda, rel:camunda-bpm-pr-594

#595 Added new index on the act_hi_varinst table
  src/main/resources/db/migration/V13__new_index_on_ActHiVarinst_table.sql
Labels: ns:camunda, prd:camunda, rel:camunda-bpm-pr-595

#607 Dtspo 14429
  infrastructure/aat.tfvars
  infrastructure/db.tf
  infrastructure/perftest.tfvars
  infrastructure/prod.tfvars
  infrastructure/variables.tf
Labels: ns:camunda, prd:camunda, add-or-update, rel:camunda-bpm-pr-607
