Repository hmcts/camunda-bpm, pull requests merged in 2024-07, with the labels that each got.

#849 Update Clean Job Schedule and Type
  src/main/resources/application.yaml
Labels: ns:camunda, prd:camunda, rel:camunda-bpm-pr-849

#859 Bumping SKU
  infrastructure/demo.tfvars
Labels: ns:camunda, prd:camunda, aat/no-changes, prod/no-changes, rel:camunda-bpm-pr-859

#861 fix: bump Camunda Prod SQL Storage
  infrastructure/prod.tfvars
Labels: ns:camunda, prd:camunda, aat/no-changes, prod/no-changes, rel:camunda-bpm-pr-861

#862 DTSSTCI-578
  src/main/resources/application.yaml
Labels: ns:camunda, prd:camunda, rel:camunda-bpm-pr-862

#866 feat: bump perftest Postgres SKU to match prod
  infrastructure/perftest.tfvars
Labels: ns:camunda, prd:camunda, aat/no-changes, prod/no-changes, rel:camunda-bpm-pr-866
