Repository hmcts/camunda-bpm, pull requests merged in 2024-03, with the labels that each got.

#761 Camunda 7.20 and Spring Boot 3 upgrade, includes fixes for conditional logic that caused bugs previously.
  .gitignore
  README.md
  build.gradle
  config/owasp/suppressions.xml
  docker-compose.yml
  src/main/java/uk/gov/hmcts/reform/camunda/bpm/config/WebSecurityApiAnonymousConfig.java
  src/main/java/uk/gov/hmcts/reform/camunda/bpm/config/WebSecurityApiConfig.java
  src/main/java/uk/gov/hmcts/reform/camunda/bpm/config/WebSecurityWebAppConfig.java
  src/main/java/uk/gov/hmcts/reform/camunda/bpm/filter/SpringSecurityApiAuthenticationProvider.java
  src/main/java/uk/gov/hmcts/reform/camunda/bpm/filter/SpringSecurityWebappAuthenticationProvider.java
  src/main/resources/application.yaml
  src/main/resources/db/migration/V14__postgres_engine_7.19_to_7.20.sql
  src/test/java/uk/gov/hmcts/reform/camunda/bpm/filter/webapp/SpringSecurityApiAuthenticationProviderTest.java
  src/test/java/uk/gov/hmcts/reform/camunda/bpm/filter/webapp/SpringSecurityWebappAuthenticationProviderTest.java
  src/testUtils/java/uk/gov/hmcts/reform/camunda/bpm/SpringBootIntegrationBaseTest.java
Labels: ns:camunda, prd:camunda, destroy, rel:camunda-bpm-pr-761

#766 Create local dev setup guide with images
  README.md
  build.gradle
  config/owasp/suppressions.xml
  images/BuildRunConfig.png
  images/configSelect.png
  images/debugMode.png
  images/dockerCompose.png
  images/editConfig.png
  images/envVars.png
  images/gradleConfig.png
  images/gradleSettings.png
  images/intellijOpen.png
  images/mainClass.png
  images/newConfig.png
  images/progressApp.png
  images/projectAddSource.png
  images/projectJavaJDK.png
  images/runApp.png
  images/runConsole.png
  images/shortcuts.png
Labels: ns:camunda, prd:camunda, add-or-update, rel:camunda-bpm-pr-766

#771 Adding an input variable for server configuration
  infrastructure/aat.tfvars
  infrastructure/db.tf
  infrastructure/ithc.tfvars
  infrastructure/perftest.tfvars
  infrastructure/prod.tfvars
  infrastructure/variables.tf
Labels: ns:camunda, prd:camunda, rel:camunda-bpm-pr-771, no-changes

#788 Postgresql Upgrade - ITHC
  infrastructure/db.tf
  infrastructure/ithc.tfvars
  infrastructure/variables.tf
Labels: ns:camunda, prd:camunda, no-changes, rel:camunda-bpm-pr-788

#789 Resync perftest with master
  Jenkinsfile_CNP
Labels: ns:camunda, prd:camunda, rel:camunda-bpm-pr-789

#791 Postgresql Upgrade - Perftest
  infrastructure/perftest.tfvars
Labels: ns:camunda, prd:camunda, no-changes, rel:camunda-bpm-pr-791

#790 Postgresql Upgrade - Demo
  infrastructure/demo.tfvars
Labels: ns:camunda, prd:camunda, no-changes, rel:camunda-bpm-pr-790

#792 Postgresql Upgrade - AAT
  infrastructure/aat.tfvars
Labels: ns:camunda, prd:camunda, add-or-update, rel:camunda-bpm-pr-792
