Repository hmcts/camunda-bpm, pull requests merged in 2024-02, with the labels that each got.

#681 Extending supression
  config/owasp/suppressions.xml
Labels: ns:camunda, prd:camunda, rel:camunda-bpm-pr-681

#738 Enable hikari keep alive every 5 mins
  src/main/resources/application.yaml
Labels: ns:camunda, prd:camunda, rel:camunda-bpm-pr-738

#741 Lower the keep alive time and set max idle time
  src/main/resources/application.yaml
Labels: ns:camunda, prd:camunda, rel:camunda-bpm-pr-741

#762 COT-742: SSCS Camunda Access
  src/main/resources/application.yaml
Labels: ns:camunda, prd:camunda, rel:camunda-bpm-pr-762
